server:
  port: 4002

spring:
  application:
    name: whxiaoyu-uc


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/admin?characterEncoding=utf8&useSSL=false
    username: root
    password:

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.189:8848

security:
  oauth2:
    client:
      client-id: xiaoyu
      client-secret: 1234
      access-token-uri: http://localhost:4001/oauth/token

    resource:
      token-info-uri: http://localhost:4001/oauth/check_token

mybatis-plus:
  # 逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/*Mapper.xml

logging:
  level:
    com.whxiaoyu.uc: debug
