server:
  port: 4001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/admin?characterEncoding=utf8&useSSL=false
    username: root
    password:

  redis:
    host: 127.0.0.1

mybatis-plus:
  global-config:
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: info,health

