spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://127.0.0.1:3306/admin?characterEncoding=utf8&useSSL=false
          username: root
          password:

        salve:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://192.168.10.189:3306/admin?characterEncoding=utf8&useSSL=false
          username: root
          password: xiaoyu123

logging:
  level:
    com.whxiaoyu.transation: debug
